openapi: 3.0.0
info:
  title: Аналитика
  description: Сбор и выдача аналитики.
  version: "0.2"
servers:
  - url: 'http://example.org/'
    description: Основной сервис аналитики
paths:
  /analytics/events/{id}:
    get:
      summary: Аналитика по событию
      description: Выдаёт аналитику по событию.
      responses:
        '200':
          description: JSON-объект.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count: # = `{ "count": 12 }`
                    type: integer
                    format: int32
                    minimum: 0
        '400':
          description: Некорректный идентификатор. # Если вместо числа передана строка
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Мероприятие с таким идентификатором не найдено.
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int32
          required: true
          description: Идентификатор мероприятия
      security:
        - OAuth2Schema:
          - read_events_analytics
  /analytics/tickets/{eventId}:
    get:
      summary: Аналитика по продажам билетов для события
      description: Выдаёт аналитику по продажам билетов для события.
      responses:
        '200':
          description: JSON-объект.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count: # = `{ "count": 12 }`
                    type: integer
                    format: int32
                    minimum: 0
        '400':
          description: Некорректный идентификатор. # Если вместо числа передана строка
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Мероприятие с таким идентификатором не найдено.
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      parameters:
        - in: path
          name: eventId
          schema:
            type: integer
            format: int32
          required: true
          description: Идентификатор мероприятия
      security:
        - OAuth2Schema:
          - read_tickets_analytics
  /analytics/users/{userId}:
    get:
      summary: Статистика активности пользователя
      responses:
        '200':
          description: JSON-объект.
          content:
            application/json:
              schema:
                type: object
                properties:
                  count: # = `{ "count": 12 }`
                    type: integer
                    format: int32
                    minimum: 0
        '400':
          description: Некорректный идентификатор. # Если вместо числа передана строка
        '403':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Пользователь с таким идентификатором не найден.
        '429':
          $ref: '#/components/responses/TooManyRequestsError'
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
            format: int32
          required: true
          description: Идентификатор пользователя
      security:
        - OAuth2Schema:
          - read_users_analytics
components:
  responses:
    UnauthorizedError:
      description: Токен авторизации отсутствует или не является корректным.
    TooManyRequestsError:
      description: Слишком частые запросы.
  securitySchemes:
    OAuth2Schema:
      type: oauth2
      description: Используется аутентификация OAuth 2.
      flows:
        implicit:
          authorizationUrl: https://example.org/oauth2/authorize
          scopes:
            read_users_analytics: Чтение аналитики о пользователях
            read_tickets_analytics: Чтение аналитики о билетах
            read_events_analytics: Чтение аналитики о мероприятиях